nelmio_cors:
  defaults:
    allow_origin: ["*"] # Permet toutes les origines
    allow_credentials: true
    allow_headers: ["*"]
    allow_methods: ["POST", "GET", "OPTIONS", "PUT", "DELETE"]
    expose_headers: []
    max_age: 3600
  paths:
    "^/": # S'applique à toutes les routes

