security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    administration:
      pattern: ^/api/administration
      stateless: true
      jwt: ~ # Utilise JWT pour l'authentification

  access_control:
    # Routes les plus spécifiques en premier
    - { path: ^/api/administration/admin, roles: ROLE_ADMIN }
    - { path: ^/api/administration/vet, roles: ROLE_VETERINAIRE }
    - { path: ^/api/administration, roles: ROLE_EMPLOYE } # Règle générique pour le reste

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
