vich_uploader:
  db_driver: orm
  twig: false
  form: false
  storage: file_system
  metadata:
    type: attribute
  mappings:
    animal_image:
      uri_prefix: /uploads/images/animaux
      upload_destination: "%kernel.project_dir%/public/uploads/images/animaux"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    habitat_image:
      uri_prefix: /uploads/images/habitats
      upload_destination: "%kernel.project_dir%/public/uploads/images/habitats"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
