version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/symfony
      - ./var/log:/var/www/symfony/var/log
    depends_on:
      - mariadb
      - mongodb
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://app:app_password@mariadb:3306/zoo_arcadia?serverVersion=mariadb-10.10.2
      - MONGODB_URL=mongodb://app:app_password@mongodb:27017/zoo_arcadia?authSource=admin

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/symfony:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  mariadb:
    image: mariadb:10.10.2
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: zoo_arcadia
      MARIADB_USER: app
      MARIADB_PASSWORD: app_password
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: app_password
      MONGO_INITDB_DATABASE: zoo_arcadia
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mariadb-data:
  mongodb-data: