name: Déploiement auto du backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connexion SSH et déploiement
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/backEndECF
            git pull origin main
            php bin/console cache:clear --env=prod
            sudo systemctl restart apache2
            sudo systemctl restart php8.2-fpm
